<?php
/** @var \M2Developer\Knockout\Block\Test $block */
?>
<label><?= __("Data retrieved from Block is") ?></label>
<h1><?= $block->getText() ?></h1>
<label><?= __("Data retrieved from Knockout template is") ?></label>
<div data-bind="scope: 'knockout-tutorial'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "knockout-tutorial": {
                        "component": "M2Developer_Knockout/js/viewModel",
                        "template" : "M2Developer_Knockout/template"
                    }
                }
            }
        }
    }
</script>
